---
namespace: telekom_mms
name: vector
version: 2.0.1
readme: README.md
authors:
  - Dimitris Zervas <dzervas@dzervas.gr>
  - Gaëtan Duchaussois <gaetan.duchaussois@fretlink.com>
  - Dylan Humphreys <dylanjhumphreys@gmail.com>
  - Daniel Uhlmann <contact@xfuture-digital.de>
  - Christopher Grau <c.grau@telekom.de>
description: >-
  This is an ansible collection to set up [vector](https://vector.dev) on various systems.
license_file: LICENSE
tags:
  - vector
  - logging
  - monitoring
dependencies:
  community.general: ">=8.6.0"
repository: https://github.com/telekom-mms/ansible-vector
documentation: https://github.com/telekom-mms/ansible-vector
homepage: https://github.com/telekom-mms/ansible-vector
issues: https://github.com/telekom-mms/ansible-vector/issues
